apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-service
  template:
    metadata:
      labels:
        app: monitoring-service
    spec:
      containers:
        - name: monitoring-service
          image: quadaraacr.azurecr.io/monitoring-service:latest
          ports:
            - containerPort: 80
          env:
            - name: SERVICE_NAME
              value: "monitoring-service"
            - name: DB_HOST
              valueFrom: {secretKeyRef: {name: quadara-db-secret, key: DB_HOST}}
            - name: DB_NAME
              valueFrom: {secretKeyRef: {name: quadara-db-secret, key: DB_NAME}}
            - name: DB_USER
              valueFrom: {secretKeyRef: {name: quadara-db-secret, key: DB_USER}}
            - name: DB_PASSWORD
              valueFrom: {secretKeyRef: {name: quadara-db-secret, key: DB_PASSWORD}}
            - name: DB_SSLMODE
              valueFrom: {secretKeyRef: {name: quadara-db-secret, key: DB_SSLMODE}}
            - name: JWT_SECRET
              valueFrom: {secretKeyRef: {name: quadara-jwt-secret, key: JWT_SECRET}}
            - name: JWT_EXPIRES_MIN
              valueFrom: {secretKeyRef: {name: quadara-jwt-secret, key: JWT_EXPIRES_MIN}}
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: default
spec:
  selector:
    app: monitoring-service
  ports:
    - port: 80
      targetPort: 80
