apiVersion: v1
kind: Secret
metadata:
  name: quadara-db-secret
  namespace: default
type: Opaque
stringData:
  DB_HOST: parental-control-db.postgres.database.azure.com
  DB_NAME: quadara_db
  DB_USER: pgadmin
  DB_PASSWORD: "{{REEMPLAZA_CON_TU_PASSWORD}}"
  DB_SSLMODE: "require"
